"""add_roadmap_token_to_player_roadmap_steps

Revision ID: 2850c6856ee1
Revises: a06fb5d973b7
Create Date: 2026-08-09 12:36:53.501984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2850c6856ee1'
down_revision: Union[str, Sequence[str], None] = 'a06fb5d973b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_roadmap_steps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roadmap_token', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_roadmap_steps', schema=None) as batch_op:
        batch_op.drop_column('roadmap_token')

    # ### end Alembic commands ###
