"""add_index_champion_scores_computed_at

Revision ID: 498c8261a47a
Revises: 792a4624e1ff
Create Date: 2026-08-16 15:44:28.564135

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "498c8261a47a"
down_revision: Union[str, Sequence[str], None] = "792a4624e1ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("champion_scores", schema=None) as batch_op:
        batch_op.create_index(
            "ix_champion_scores_computed_at", ["computed_at"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("champion_scores", schema=None) as batch_op:
        batch_op.drop_index("ix_champion_scores_computed_at")

    # ### end Alembic commands ###
