"""add_match_participant_stats

Revision ID: 792a4624e1ff
Revises: 2850c6856ee1
Create Date: 2026-08-12 01:37:38.385769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792a4624e1ff'
down_revision: Union[str, Sequence[str], None] = '2850c6856ee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_cs', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gold_earned', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_to_champions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('damage_taken', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vision_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('double_kills', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('triple_kills', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quadra_kills', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('penta_kills', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kill_participation', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('team_damage_percentage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_participants', schema=None) as batch_op:
        batch_op.drop_column('team_damage_percentage')
        batch_op.drop_column('kill_participation')
        batch_op.drop_column('penta_kills')
        batch_op.drop_column('quadra_kills')
        batch_op.drop_column('triple_kills')
        batch_op.drop_column('double_kills')
        batch_op.drop_column('vision_score')
        batch_op.drop_column('damage_taken')
        batch_op.drop_column('damage_to_champions')
        batch_op.drop_column('gold_earned')
        batch_op.drop_column('total_cs')

    # ### end Alembic commands ###
