"""add_player_roadmap_steps

Revision ID: a06fb5d973b7
Revises: 83b9214bdd2b
Create Date: 2026-08-09 01:21:33.086995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a06fb5d973b7'
down_revision: Union[str, Sequence[str], None] = '83b9214bdd2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_roadmap_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_name_key', sa.String(), nullable=False),
    sa.Column('tag_line_key', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('champion_id', sa.String(), nullable=False),
    sa.Column('lane', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('delta_pct_inicial', sa.Float(), nullable=False),
    sa.Column('delta_pct_atual', sa.Float(), nullable=False),
    sa.Column('partidas_base', sa.Integer(), nullable=False),
    sa.Column('partidas_atual', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_name_key', 'tag_line_key', 'region', 'champion_id', 'lane', name='uq_player_roadmap_steps')
    )
    with op.batch_alter_table('player_roadmap_steps', schema=None) as batch_op:
        batch_op.create_index('ix_player_roadmap_steps_identity', ['game_name_key', 'tag_line_key', 'region'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_roadmap_steps', schema=None) as batch_op:
        batch_op.drop_index('ix_player_roadmap_steps_identity')

    op.drop_table('player_roadmap_steps')
    # ### end Alembic commands ###
