"""add_player_rank_snapshots

Revision ID: af03c204eca1
Revises: 498c8261a47a
Create Date: 2026-08-16 20:04:55.314018

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af03c204eca1"
down_revision: Union[str, Sequence[str], None] = "498c8261a47a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_rank_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_name_key", sa.String(), nullable=False),
        sa.Column("tag_line_key", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("queue_type", sa.String(), nullable=False),
        sa.Column("tier", sa.String(), nullable=False),
        sa.Column("division", sa.String(), nullable=False),
        sa.Column("league_points", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=False),
        sa.Column("losses", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("player_rank_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_player_rank_snapshots_identity",
            ["game_name_key", "tag_line_key", "region", "queue_type", "captured_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_rank_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_player_rank_snapshots_identity")

    op.drop_table("player_rank_snapshots")
    # ### end Alembic commands ###
