"""add_player_champion_mastery_snapshots

Revision ID: d2945b83d6c5
Revises: af03c204eca1
Create Date: 2026-08-17 00:30:10.998255

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d2945b83d6c5"
down_revision: Union[str, Sequence[str], None] = "af03c204eca1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "player_champion_mastery_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("puuid", sa.String(), nullable=False),
        sa.Column("champion_id", sa.String(), nullable=False),
        sa.Column("concentracao", sa.Float(), nullable=False),
        sa.Column("pontos_campeao_lider", sa.Integer(), nullable=False),
        sa.Column("pontos_totais", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table(
        "player_champion_mastery_snapshots", schema=None
    ) as batch_op:
        batch_op.create_index(
            "ix_player_champion_mastery_snapshots_puuid",
            ["puuid", "captured_at"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "player_champion_mastery_snapshots", schema=None
    ) as batch_op:
        batch_op.drop_index("ix_player_champion_mastery_snapshots_puuid")

    op.drop_table("player_champion_mastery_snapshots")
    # ### end Alembic commands ###
