"""add_index_player_rankings_game_name

Revision ID: f7b953661fbb
Revises: d2945b83d6c5
Create Date: 2026-08-22 00:01:49.775851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7b953661fbb"
down_revision: Union[str, Sequence[str], None] = "d2945b83d6c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_rankings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_player_rankings_game_name", ["game_name"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("player_rankings", schema=None) as batch_op:
        batch_op.drop_index("ix_player_rankings_game_name")

    # ### end Alembic commands ###
